# Configuration Settings for 4-M8P device

debug: 2                    # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM0
frame_id: m8t_base
dynamic_model: stationary   # Velocity restricted to 0 m/s. Zero dynamics 
                            # assumed.
fix_mode: auto

rate: 1                     # Measurement rate in Hz
nav_rate: 1                 # in number of measurement cycles

uart1:
  baudrate: 9600           # C94-M8P specific
  in: 0                     # No UART in for base
  out: 0                   # RTCM 3

inf: 
  all: true               # Whether to display all INF messages in console

# Enable u-blox message publishers
publish:
  tim:
    tm2: true 
