# Configuration Settings for C94-M8P device
ublox_gps_rover_node:
  ros__parameters:
    debug: 4                    # Range 0-4 (0 means no debug statements will print)

    device: /dev/serial/by-id/usb-u-blox_AG_-_www.u-blox.com_u-blox_GNSS_receiver_F9H-if00
    frame_id: gps_rover

    uart1:
      baudrate: 115200

    config_on_startup: false    # If false, the node will not override configurations of the device on startup
                                # Device should be configured with u-center and configurations should be saved in flash
                                # Please use the configuration file provided by Lemvos
    
    # Enable u-blox message publishers
    publish:
      all: false
      aid:
        hui: false
      nav:
        relposned: true

