//==============================================================================
// Copyright (c) 2012, Johannes Meyer, TU Darmstadt
// All rights reserved.

// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the Flight Systems and Automatic Control group,
//       TU Darmstadt, nor the names of its contributors may be used to
//       endorse or promote products derived from this software without
//       specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//==============================================================================

#ifndef UBLOX_GPS_H
#define UBLOX_GPS_H

#include <map>
#include <vector>
#include <locale>
#include <stdexcept>

#include <boost/asio/ip/tcp.hpp>
#include <boost/asio/serial_port.hpp>
#include <boost/regex.hpp>
#include <boost/asio/io_service.hpp>
#include <boost/atomic.hpp>
#include <boost/thread/mutex.hpp>


#include <ros/console.h>

#include <ublox/serialization/ublox_msgs.h>

#include <ublox_gps/async_worker.h>
#include <ublox_gps/callback.h>

namespace ublox_gps {
// Possible baudrates for U-Blox devices
const static unsigned int kBaudrates[] = {4800, 9600, 19200, 38400, 
                                          57600, 115200, 230400, 460800};

class Gps {
 public:
  const static int kSetBaudrateSleepMs = 500;
  const static double kDefaultAckTimeout = 1.0;
  const static int kWriterSize = 1024;

  Gps();
  virtual ~Gps();

  /**
   * @brief Initialize the I/O port, if TCP, baudrate, and uart_in/uart_out 
   * values will be ignored.
   * @param baudrate the desired baudrate of the port
   * @param uart_in The UART in protocol, see CfgPRT for values
   * @param uart_in The UART out protocol, see CfgPRT for values
   */
  void initializeIo(std::string device,
                    unsigned int baudrate,
                    uint16_t uart_in,
                    uint16_t uart_out);
  /**
   * @brief Closes the I/O port.
   */
  void close();

  /**
   * @brief Send a reset message to the u-blox-device
   * @param nav_bbr_mask The BBR sections to clear, see CfgRST message
   * @param reset_mode The reset type, see CfgRST message
   * @return true if the message was successfully sent, false otherwise
   */
  bool reset(uint16_t nav_bbr_mask, uint16_t reset_mode);
  
  /**
   * @brief Configure the UART1 Port.
   * @param ids the baudrate of the port
   * @param in_proto_mask the in protocol mask, see CfgPRT message
   * @param out_proto_mask the out protocol mask, see CfgPRT message
   * @return true on ACK, false on other conditions.
   */
  bool configUart1(unsigned int baudrate, uint16_t in_proto_mask, 
                   uint16_t out_proto_mask);

  /**
   * @brief Disable the UART Port. Sets in/out protocol masks to 0. Does not 
   * modify other values.
   * @param prev_cfg an empty message which will be filled with the previous
   * configuration parameters
   * @return true on ACK, false on other conditions.
   */
  bool disableUart1(ublox_msgs::CfgPRT& prev_cfg);

  /**
   * @brief Configure the device navigation and measurement rate settings.
   * @param meas_rate Period in milliseconds between subsequent measurements.
   * @param nav_rate the rate at which navigation solutions are generated by the
   * receiver in number measurement cycles
   * @return true on ACK, false on other conditions.
   */
  bool configRate(uint16_t meas_rate, uint16_t nav_rate);

  /**
   * @brief Configure the RTCM messages with the given IDs to the set rate.
   * @param ids the RTCM message ids, valid range: [0, 255]
   * @param rates the send rates for each RTCM message ID, valid range: [0, 255]
   * @return true on ACK, false on other conditions.
   */
  bool configRtcm(std::vector<uint8_t> ids, std::vector<uint8_t> rates);

  /**
   * @brief Configure the SBAS settings.
   * @param enable If true, enable SBAS. Deprecated in firmware 8, use CfgGNSS
   * instead.
   * @param usage SBAS usage, see CfgSBAS for options
   * @param max_sbas Maximum Number of SBAS prioritized tracking channels
   * @return true on ACK, false on other conditions.
   */
  bool configSbas(bool enable, uint8_t usage, uint8_t max_sbas);

  /**
   * @brief Set the TMODE3 settings to fixed at the given antenna reference
   * point (ARP) position in either Latitude Longitude Altitude (LLA) or 
   * ECEF coordinates.
   * @param arp_position a vector of size 3 representing the ARP position in 
   * ECEF coordinates [m] or LLA coordinates [deg]
   * @param arp_position_hp a vector of size 3 a vector of size 3 representing  
   * the ARP position in ECEF coordinates [m] or LLA coordinates [deg]
   * @param lla_flag true if position is given in LAT/LON/ALT, false if ECEF
   * @param fixed_pos_acc Fixed position 3D accuracy [m]
   * @return true on ACK, false if settings are incorrect or on other conditions
   */
  bool configTmode3Fixed(bool lla_flag,
                         std::vector<float> arp_position, 
                         std::vector<float> arp_position_hp,
                         float fixed_pos_acc);

  /**
   * @brief Set the TMODE3 settings to survey-in.
   * @param svin_min_dur Survey-in minimum duration [s]
   * @param svin_acc_limit Survey-in position accuracy limit [m]
   * @return true on ACK, false on other conditions.
   */
  bool configTmode3SurveyIn(unsigned int svin_min_dur, float svin_acc_limit);

  /**
   * @brief Set the TMODE3 settings to disabled. Should only be called for
   * High Precision GNSS devices, otherwise the device will return a NACK.
   * @return true on ACK, false on other conditions.
   */
  bool disableTmode3();

  /**
   * @brief Set the rate at which the U-Blox device sends the given message
   * @param class_id the class identifier of the message
   * @param message_id the message identifier
   * @param rate the updated rate in Hz
   * @return true on ACK, false on other conditions.
   */
  bool setRate(uint8_t class_id, uint8_t message_id, uint8_t rate);

  /**
   * @brief Set the device dynamic model.
   * @param model Dynamic model to use. Consult ublox protocol spec for details.
   * @return true on ACK, false on other conditions.
   */
  bool setDynamicModel(uint8_t model);

  /**
   * @brief Set the device fix mode.
   * @param mode 2D only, 3D only or auto.
   * @return true on ACK, false on other conditions.
   */
  bool setFixMode(uint8_t mode);

  /**
   * @brief Set the dead reckoning time limit
   * @param limit Time limit in seconds.
   * @return true on ACK, false on other conditions.
   */
  bool setDeadReckonLimit(uint8_t limit);

  /**
   * @brief Enable or disable PPP (precise-point-positioning).
   * @param enable If true, enable PPP.
   * @return true on ACK, false on other conditions.
   *
   * @note This is part of the expert settings. It is recommended you check
   * the ublox manual first.
   */
  bool setPpp(bool enable);

  /**
   * @brief Set the DGNSS mode (see CfgDGNSS message for details).
   * @param mode the DGNSS mode (see CfgDGNSS message for options)
   * @return true on ACK, false on other conditions
   */
  bool setDgnss(uint8_t mode);

  /**
   * @brief Enable or disable ADR (automotive dead reckoning).
   * @param enable If true, enable ADR.
   * @return true on ACK, false on other conditions.
   */
  bool setUseAdr(bool enable);

  /**
   * @brief Configure the U-Blox send rate of the message & subscribe to the 
   * given message
   * @param the callback handler for the message
   * @param rate the rate in Hz of the message
   * @return
   */
  template <typename T>
  Callbacks::iterator subscribe(typename CallbackHandler_<T>::Callback callback,
                                unsigned int rate);
  /**
   * @brief Subscribe to the given Ublox message.
   * @param the callback handler for the message
   * @return
   */
  template <typename T>
  Callbacks::iterator subscribe(
      typename CallbackHandler_<T>::Callback callback);

  /**
   * @brief Subscribe to the message with the given ID. This is used for 
   * messages which have the same format but different message IDs, 
   * e.g. INF messages.
   * @param the callback handler for the message
   * @param message_id the U-Blox message ID
   * @return
   */
  template <typename T>
  Callbacks::iterator subscribeId(
      typename CallbackHandler_<T>::Callback callback, 
      unsigned int message_id);

  /**
   * Read a u-blox message of the given type.
   * @param message the received u-blox message
   * @param timeout the amount of time to wait for the desired message
   */
  template <typename T>
  bool read(T& message,
            const boost::posix_time::time_duration& timeout = default_timeout_);

  bool isInitialized() const { return worker_ != 0; }
  bool isConfigured() const { return isInitialized() && configured_; }
  bool isOpen() const { return worker_->isOpen(); }

  /**
   * Poll a u-blox message of the given type.
   * @param message the received u-blox message output
   * @param payload the poll message payload sent to the device
   * defaults to empty
   * @param timeout the amount of time to wait for the desired message
   */
  template <typename ConfigT>
  bool poll(ConfigT& message,
            const std::vector<uint8_t>& payload = std::vector<uint8_t>(),
            const boost::posix_time::time_duration& timeout = default_timeout_);
  /**
   * Poll a u-blox message.
   * @param class_id the u-blox message class id
   * @param message_id the u-blox message id
   * @param payload the poll message payload sent to the device,
   * defaults to empty
   * @param timeout the amount of time to wait for the desired message
   */
  bool poll(uint8_t class_id, uint8_t message_id,
            const std::vector<uint8_t>& payload = std::vector<uint8_t>());

  /**
   * @brief Send the given configuration message.
   * @param message the configuration message
   * @param wait if true, wait for an ACK
   * @return true if message sent successfully and either ACK was received or 
   * wait was set to false
   */
  template <typename ConfigT>
  bool configure(const ConfigT& message, bool wait = true);

  /**
   * @brief Wait for an acknowledge message until the timeout
   * @param timeout maximum time to wait in seconds
   * @param class_id the expected class ID of the ACK
   * @param msg_id the expected message ID of the ACK
   * @return true if expected ACK received, false otherwise
   */
  bool waitForAcknowledge(const boost::posix_time::time_duration& timeout, 
                          uint8_t class_id, uint8_t msg_id);

 private:
  // Types for ACK/NACK messages, WAIT is used when waiting for an ACK
  enum AckType { NACK, ACK, WAIT }; 
  
  // Stores ACK/NACK messages
  struct Ack {
    AckType type;
    uint8_t msg_id;
    uint8_t class_id;
  };

  void setWorker(const boost::shared_ptr<Worker>& worker);
  
  /**
   * @brief Initialize TCP I/O.
   */
  void initializeTcp();
  
  /**
   * @brief Initialize the Serial I/O port.
   * @param baudrate the desired baud rate of the port
   * @param uart_in the UART In protocol, see CfgPRT for options
   * @param uart_out the UART Out protocol, see CfgPRT for options
   */
  void initializeSerial(unsigned int baudrate,
                        uint16_t uart_in,
                        uint16_t uart_out);
  /**
   * @brief Processes u-blox messages in the given buffer & clears the read
   * messages from the buffer.
   * @param data the buffer of u-blox messages to process
   * @param size the size of the buffer
   */
  void readCallback(unsigned char* data, std::size_t& size);

  boost::shared_ptr<Worker> worker_;
  bool configured_;

  static boost::posix_time::time_duration default_timeout_;
  // Stores last received ACK, accessed by multiple threads
  mutable boost::atomic<Ack> ack_;

  Callbacks callbacks_;
  boost::mutex callback_mutex_;

  // Asynchronous IO objects
  boost::asio::io_service io_service_;
  boost::shared_ptr<boost::asio::serial_port> serial_handle_;
  boost::shared_ptr<boost::asio::ip::tcp::socket> tcp_handle_;
};

template <typename T>
Callbacks::iterator Gps::subscribe(
    typename CallbackHandler_<T>::Callback callback, unsigned int rate) {
  if (!setRate(T::CLASS_ID, T::MESSAGE_ID, rate)) return Callbacks::iterator();
  return subscribe<T>(callback);
}

template <typename T>
Callbacks::iterator Gps::subscribe(
    typename CallbackHandler_<T>::Callback callback) {
  boost::mutex::scoped_lock lock(callback_mutex_);
  CallbackHandler_<T>* handler = new CallbackHandler_<T>(callback);
  return callbacks_.insert(
      std::make_pair(std::make_pair(T::CLASS_ID, T::MESSAGE_ID),
                     boost::shared_ptr<CallbackHandler>(handler)));
}

template <typename T>
Callbacks::iterator Gps::subscribeId(
    typename CallbackHandler_<T>::Callback callback, unsigned int message_id) {
  boost::mutex::scoped_lock lock(callback_mutex_);
  CallbackHandler_<T>* handler = new CallbackHandler_<T>(callback);
  return callbacks_.insert(
      std::make_pair(std::make_pair(T::CLASS_ID, message_id),
                     boost::shared_ptr<CallbackHandler>(handler)));
}

template <typename ConfigT>
bool Gps::poll(ConfigT& message,
               const std::vector<uint8_t>& payload,
               const boost::posix_time::time_duration& timeout) {
  if (!poll(ConfigT::CLASS_ID, ConfigT::MESSAGE_ID, payload)) return false;
  return read(message, timeout);
}

template <typename T>
bool Gps::read(T& message, const boost::posix_time::time_duration& timeout) {
  bool result = false;
  if (!worker_) return false;

  // Create a callback handler for this message
  callback_mutex_.lock();
  CallbackHandler_<T>* handler = new CallbackHandler_<T>();
  Callbacks::iterator callback = callbacks_.insert(
      (std::make_pair(std::make_pair(T::CLASS_ID, T::MESSAGE_ID),
                      boost::shared_ptr<CallbackHandler>(handler))));
  callback_mutex_.unlock();
  // Wait for the message
  if (handler->wait(timeout)) {
    message = handler->get();
    result = true;
  }
  // Remove the callback handler
  callback_mutex_.lock();
  callbacks_.erase(callback);
  callback_mutex_.unlock();
  return result;
}

template <typename ConfigT>
bool Gps::configure(const ConfigT& message, bool wait) {
  if (!worker_) return false;

  // Reset ack
  Ack ack;
  ack.type = WAIT;
  ack_.store(ack, boost::memory_order_seq_cst);

  // Encode the message
  std::vector<unsigned char> out(kWriterSize);
  ublox::Writer writer(out.data(), out.size());
  if (!writer.write(message)) {
    ROS_ERROR("Failed to encode config message 0x%02x / 0x%02x", 
              message.CLASS_ID, message.MESSAGE_ID);
    return false;
  }
  // Send the message to the device
  worker_->send(out.data(), writer.end() - out.data());

  if (!wait) return true;

  // Wait for an acknowledgment and return whether or not it was received
  return waitForAcknowledge(default_timeout_, 
                            message.CLASS_ID,
                            message.MESSAGE_ID);
}

}  // namespace ublox_gps

#endif  // UBLOX_GPS_H
